---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localstack
  namespace: default
spec:
  chart:
    spec:
      chart: localstack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: localstack
        namespace: flux-system
  interval: 30s
